# General settings
name: 'csd_dual_lrrk2'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'offline'             # online | offline | disabled
gpus: 2                   # Multi-gpu is not implemented on this branch
guidance_target: 'EdgeComCondMulti'
regressor: True

# resume: '../outputs/2024-12-16/20-28-18-moses_dual_hpk1/checkpoints/moses_dual_hpk1_resume/last.ckpt'    
resume: null        # If resume, path to ckpt file from outputs directory in main directory
test_only: null
# test_only: '/raid/yyw/PharmDiGress/outputs/2024-12-16/20-28-18-moses_dual_hpk1/checkpoints/moses_dual_hpk1_resume/last.ckpt'         # Use absolute path

check_val_every_n_epochs: 1
sample_every_val: 1
# val_check_interval: 200
samples_to_generate: 128       # We advise to set it to 2 x batch_size maximum
samples_to_save: 20
chains_to_save: 1
log_every_steps: 20
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 1000
final_model_samples_to_save: 200
final_model_chains_to_save: 1
# final_model_samples_to_generate: 3
# final_model_samples_to_save: 2
# final_model_chains_to_save: 1

evaluate_all_checkpoints: False