# General settings
name: 'moses_dual'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'offline'             # online | offline | disabled
gpus: 2                    # Multi-gpu is not implemented on this branch
guidance_target: 'EdgeComCondMulti'
regressor: True

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null
# test_only: '/raid/yyw/PharmDiGress/outputs/2024-05-08/15-59-16-qm9_dual/checkpoints/qm9_dual_resume/last.ckpt'         # Use absolute path

check_val_every_n_epochs: 5
sample_every_val: 4
val_check_interval: 100
samples_to_generate: 512       # We advise to set it to 2 x batch_size maximum
samples_to_save: 20
chains_to_save: 5
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 18000
final_model_samples_to_save: 50
final_model_chains_to_save: 5
# final_model_samples_to_generate: 3
# final_model_samples_to_save: 2
# final_model_chains_to_save: 1

evaluate_all_checkpoints: False