# Model settings
type: 'discrete'
transition: 'marginal'                          # uniform or marginal
model: 'graph_pos_com'
diffusion_steps: 500
diffusion_noise_schedule: 'cosine'              # 'cosine', 'polynomial_2', 'sigmoid'
n_layers: 12 # csd: 12 qm9:8


extra_features: 'all'        # 'all', 'cycles', 'eigenvalues' or null

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
# At the moment (03/08), y contains quite little information
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 256, 'pos': 64}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 256, 'de': 64, 'dy': 128, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 256}

# lambda_train: [0.0738, 0.2828, 0.6434]
lambda_train: [5, 0]

# EGNNSparseNetwork
# train: True
# num_convs: 6 # global 6 local 4(geom) 6(qm9) 6(csd)
# num_convs_local: 4
# num_atom: 15  # with_h: 6, without_h: 5, csd: 15, moses_no_h: 8 moses_h:9
# hidden_dim: 256
# soft_edge: True
# norm_coors: True
# mlp_act: 'relu'
# cutoff: 10
# num_diffusion_timesteps: 1000
# edge_encoder: 'mlp'
# smooth_conv: False
# beta_schedule: 'sigmoid'
# beta_start: 1.e-7
# beta_end: 2.e-3
# context: ['glp1_score', 'SA', 'QED', 'acute_tox']
# context: ['gap', 'mu', 'SA', 'QED'] #qm9

# LEFTNet
num_layers: 6
hidden_channels: 64
num_radial: 32
cutoff: 10
num_atomic: 53  #csd:53 moses: 35 qm9:9
pos_require_grad: True
# context: ['gap', 'mu', 'homo', 'lumo']
context: ['lrrk2_score', 'SA', 'QED', 'acute_tox']