name: 'csd'
datadir: 'data/csd/'                 # Relative to the moses_dataset.py file
remove_h: True
filter: False
pin_memory: False
atom_type_to_atomic_number: {0: 5,1: 6,2: 7,3: 8,4: 9,5: 12,6: 15,7: 16,8: 17, 9: 20,10: 35,11: 53,12: 56}