name: 'csd'
datadir: 'data/csd/'                 # Relative to the moses_dataset.py file
remove_h: False
filter: False
pin_memory: True
# atom_type_to_atomic_number: {0: 1, 1: 6,2: 7,3: 8,4: 9,5: 15,6: 16,7: 17, 8: 35,9: 53}   #with h
atom_type_to_atomic_number: {0: 6,1: 7,2: 8,3: 9,4: 15,5: 16,6: 17,7: 35,8: 53, 9:1}