name: 'guacamol'
datadir: 'data/guacamol/guacamol_pyg/'       # Relative to the guacamol_dataset.py file
remove_h: null
filter: True                      # Use the filtered version or the raw guacamol file
atom_type_to_atomic_number: {0: 1,1: 5,2: 6,3: 7,4: 8,5: 9,6: 12,7: 15,8: 16,9: 17, 10: 20,11: 35,12: 53,13: 56}