name: 'moses'
datadir: 'data/moses/moses_pyg/'                 # Relative to the moses_dataset.py file
remove_h: True
filter: False
phore: ['Aromatic', 'Hydrophobe', 'Acceptor', 'Donor']
atom_type_to_atomic_number: {0: 6, 1: 7, 2: 8, 3: 9, 4: 16, 5: 17, 6: 35}