# Training settings
n_epochs: 1000
batch_size: 128  # qm9:1024, csd: 64
lr: 4e-4 #csd, moses: 2e-4 qm9:0.0002
clip_grad: 0.2          # float, null to disable
save_model: True
num_workers: 8
ema_decay: 0           # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
progress_bar: false
weight_decay: 1e-12
optimizer: adamw # adamw,nadamw,nadam => nadamw for large batches, see http://arxiv.org/abs/2102.06356 for the use of nesterov momentum with large batches
seed: 0
 